### PR TITLE
added navbar with dropdown

### PR DESCRIPTION
**Pull request by ash1895-web**
This code will add the navbar with dropdown.

### CODE REVIEW

**Review by TimA314 — CHANGES_REQUESTED** [review]
Hi this is great! However, following react naming convention file names should be that of the compenent. index.js is primarily used as a main file indexing other files or components. 

Could you change the file names to Dropdown.css, Dropdown.js, Navbar.css, & Navbar.js

**Comment by TimA314** [comment]
Everything looks great now! I just need you to resolve the conflicts in the package-lock.json file. You can just accept both changes or just the incoming changes if you did not make any changes to the file. You can do this in VS Code on the source control tab. Once the conflict is resolved do the pull request again. Let me know if you have any issues.

**Comment by ash1895-web** [comment]
Hey Tim, After pulling the lastest changes, It seems the navbar had undergone some changes in CSS. And is now started looking unpleasant. I think it's a good time to introduce some standardisation w.r.t. CSS.

**Comment by TimA314** [comment]
> Hey Tim, After pulling the lastest changes, It seems the navbar had undergone some changes in CSS. And is now started looking unpleasant. I think it's a good time to introduce some standardisation w.r.t. CSS.

I think you are right. We could create a contribution file to detail coding standards such as this. Also we would want to open an issue to fix any current code to match said standard. 

Would you be willing to do this? If not you can submit your code as is and I can see about the best way to implement a standard. 

Thanks for your contribution!

**Comment by TimA314** [comment]
btw I believe these changes are the result of bootstrap being installed.

**Comment by ash1895-web** [comment]
I think going with something generic and raw will help made Dev-training-ground more scalable in future (If that turns out to be a case). I prefer CSS (or with a CSS preprocessor) over bootstrap.

**Comment by ash1895-web** [comment]
If I got some idea, will be happy to contribute again.

**Pull request merged**
